name: mcw
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_plugin:
    git:
      url: ssh://git@github.com/CybexDex/MCW-Plugin.git
      ref: develop
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.6+1
  path: ^1.6.2
  provider: ^3.0.0+1
  dio: ^2.1.13
  qr_flutter: ^2.1.0+55
  flutter_spinkit: ^3.1.0
  oktoast: ^2.2.0
  shared_preferences: ^0.5.3+2
  rflutter_alert: ^1.0.3
  cached_network_image: ^1.0.0
  rosetta: ^0.1.2
  pointycastle: ^1.0.1
  logger: ^0.7.0+2
  flutter_screenutil: ^0.5.3
  rxdart: ^0.22.0
  get_it: ^1.0.3+2
  keyboard_avoider: ^0.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  rosetta_generator: ^0.1.2
  build_runner: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - i18n/
    # assets begin
    # assets/*
    - assets/icTabPay.png
    # assets end
    
